# Generated by Django 6.0.5 on 2026-08-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="approved_by",
        ),
    ]
