# Generated by Django 6.0.5 on 2026-08-25 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="log_retention_days",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Хранить логи дестинаций (дней)",
            ),
        ),
    ]
