# Generated by Django 6.0.5 on 2026-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_log_retention_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_on_push_error",
            field=models.BooleanField(
                default=False,
                help_text="Письмо придёт не чаще раза на инцидент — при переходе дестинации в статус «Ошибка», а не на каждую повторную попытку.",
                verbose_name="Уведомлять на email при ошибке пуша",
            ),
        ),
    ]
