# Generated by Django 6.0.5 on 2026-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_notify_on_push_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_telegram_on_push_error",
            field=models.BooleanField(
                default=False,
                help_text="Нужно сначала привязать Telegram ниже. Тот же принцип «раз на инцидент», что и у email-уведомлений.",
                verbose_name="Уведомлять в Telegram при ошибке пуша",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Telegram chat ID"
            ),
        ),
    ]
