# Generated by Django 6.0.5 on 2026-08-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_notify_telegram_on_push_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_end_broadcast_on_drop",
            field=models.BooleanField(
                default=False,
                help_text="Если выключено — пропадание сигнала без нажатия «Завершить эфир» на странице потока считается необъявленным обрывом и уведомляет вас (см. уведомления об ошибке пуша выше). Если включено — эфир просто считается законченным, без уведомления.",
                verbose_name="Считать эфир завершённым автоматически при пропадании сигнала",
            ),
        ),
    ]
