# Generated by Django 6.0.5 on 2026-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_auto_end_broadcast_on_drop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auto_end_broadcast_on_drop",
            field=models.BooleanField(
                default=True,
                help_text="Включено — пропадание сигнала само по себе считается концом эфира, без уведомления. Выключите, чтобы обрыв связи или сбой энкодера без нажатия «Завершить эфир» на странице потока считался инцидентом и уведомлял вас (см. уведомления об ошибке пуша выше).",
                verbose_name="Считать эфир завершённым автоматически при пропадании сигнала",
            ),
        ),
    ]
