# Generated by Django 6.0.5 on 2026-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_auto_end_broadcast_on_drop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auto_end_broadcast_on_drop",
        ),
        migrations.AddField(
            model_name="user",
            name="broadcast_end_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Автоматически по завершению публикации"),
                    (
                        "button",
                        "Только по кнопке «Завершить эфир» (иначе — уведомление об обрыве)",
                    ),
                ],
                default="auto",
                max_length=10,
                verbose_name="Как считать эфир завершённым",
            ),
        ),
    ]
