# Generated by Django 6.0.5 on 2026-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RTMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "socialmedia_name",
                    models.CharField(
                        max_length=100, verbose_name="Название соц сети для рестрима"
                    ),
                ),
                (
                    "socialmedia_url",
                    models.URLField(verbose_name="Адрес для просмотра"),
                ),
                (
                    "socialmedia_rtmp_link",
                    models.CharField(max_length=100, verbose_name="RTMP адрес"),
                ),
                (
                    "socialmedia_rtmp_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="RTMP ключ"
                    ),
                ),
            ],
        ),
    ]
