# Generated by Django 6.0.5 on 2026-08-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_stream_rtmp_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rtmp",
            name="socialmedia_rtmp_key",
            field=models.CharField(max_length=100, verbose_name="RTMP ключ"),
        ),
        migrations.AlterUniqueTogether(
            name="rtmp",
            unique_together={("stream", "socialmedia_rtmp_key")},
        ),
    ]
