# Generated by Django 6.0.5 on 2026-08-22 16:39

import crud.fields
from django.db import migrations


def encrypt_existing_keys(apps, schema_editor):
    # Значения, записанные до перехода на EncryptedCharField, лежат в
    # колонке открытым текстом. from_db_value этого поля при чтении
    # незашифрованного значения ловит InvalidToken и отдаёт его как есть
    # (см. crud/fields.py) — так что здесь достаточно перечитать и
    # пересохранить каждую запись: read вернёт исходный plaintext, save
    # зашифрует его при записи. Идемпотентно и для уже зашифрованных строк.
    Rtmp = apps.get_model("crud", "Rtmp")
    for destination in Rtmp.objects.all():
        destination.save(update_fields=["socialmedia_rtmp_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0003_alter_rtmp_socialmedia_rtmp_key_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rtmp",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="rtmp",
            name="socialmedia_rtmp_key",
            field=crud.fields.EncryptedCharField(
                max_length=500, verbose_name="RTMP ключ"
            ),
        ),
        migrations.RunPython(encrypt_existing_keys, migrations.RunPython.noop),
    ]
