# Generated by Django 6.0.5 on 2026-08-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_alter_rtmp_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtmp",
            name="push_status",
            field=models.CharField(
                choices=[
                    ("unknown", "—"),
                    ("live", "В эфире"),
                    ("error", "Ошибка"),
                    ("stopped", "Остановлено"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="rtmp",
            name="push_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
