# Generated by Django 6.0.5 on 2026-08-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_rtmp_push_status_rtmp_push_status_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rtmp",
            name="socialmedia_url",
            field=models.URLField(blank=True, verbose_name="Адрес для просмотра"),
        ),
    ]
