# Generated by Django 6.0.5 on 2026-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0006_alter_rtmp_socialmedia_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtmp",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Рестримить"),
        ),
    ]
