# Generated by Django 6.0.5 on 2026-08-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0007_rtmp_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="youtube_chat_video_id",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="YouTube Video ID для чата"
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(choices=[("youtube", "YouTube")], max_length=10),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("author_name", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("posted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="crud.stream",
                    ),
                ),
            ],
            options={
                "ordering": ["posted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stream", "platform", "external_id"),
                        name="unique_chat_message_per_stream_platform",
                    )
                ],
            },
        ),
    ]
