# Generated by Django 6.0.5 on 2026-08-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0008_stream_youtube_chat_video_id_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="expected_live",
            field=models.BooleanField(default=False),
        ),
    ]
