# Generated by Django 6.0.5 on 2026-09-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0009_stream_expected_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="zero_bandwidth_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
